SELECT 
EMPLOYEEID,EMP.EMPLOYEE_NAME,
EMP.AOFFICE,
D.DEPARTMENT_NAME	   
	FROM 
T_G_EMPLOYEES EMP
LEFT OUTER JOIN T_G_DEPARTMENT D WITH (NOLOCK) ON EMP.DEPARTMENTID=D.DEPARTMENTID



/*
SELECT * FROM T_G_ACCESSLEVEL ORDER BY 1
------------------------------
View->1
Add->2
Modify->4
Delete->8
Print->16
------------------------------
View+Add->3
View+Modify->5
View+Delete->9
View+Print->17
------------------------------
Add+Modify->6
Add+Delete->10
Add+Print ->18
------------------------------
Modify+Delete->12
Modify+Print ->20
------------------------------
Delete+Print->24
------------------------------
View+Add+Modify->7
------------------------------
View+Add+Delete->11
------------------------------
View+Add+Modify+Delete->15
------------------------------
View+Add+Print->19
------------------------------
View+Modify+Print->21
------------------------------
View+Add+Modify+Print->23
------------------------------
View+Delete+Print->25
------------------------------
View+Add+Delete+Print->27
------------------------------
Add+Modify+Delete+Print->29
------------------------------
Add+Modify+Delete+View->31
------------------------------
*/
SELECT 
C.AOFFICE,
C.EMPLOYEEID,
C.EMPLOYEE_NAME,C.SEC_GROUP,C.SECURITYOPTIONSUBNAME,
VALUE
,'PERMISSIONS'=CASE 
WHEN VALUE IS NULL THEN ''
WHEN VALUE=1 THEN 'V'
WHEN VALUE BETWEEN 2 AND 3 THEN 'V,A'
WHEN VALUE BETWEEN 4 AND 5 THEN 'V,M'
WHEN VALUE BETWEEN 6 AND 7 THEN 'V,M,A'
WHEN VALUE BETWEEN 8 AND 9 THEN 'V,D'
WHEN VALUE BETWEEN 10 AND 11 THEN 'V,D,A'
WHEN VALUE BETWEEN 12 AND 13 THEN 'V,D,M'
WHEN VALUE BETWEEN 14 AND 15 THEN 'V,D,M,A'
WHEN VALUE BETWEEN 16 AND 17 THEN 'V,P'
WHEN VALUE BETWEEN 18 AND 19 THEN 'V,P,A'
WHEN VALUE BETWEEN 20 AND 21 THEN 'V,P,M'
WHEN VALUE BETWEEN 22 AND 23 THEN 'V,P,A,M'
WHEN VALUE BETWEEN 24 AND 25 THEN 'V,P,D'
WHEN VALUE BETWEEN 26 AND 27 THEN 'V,P,D,A'
WHEN VALUE BETWEEN 28 AND 29 THEN 'V,P,D,M'
WHEN VALUE BETWEEN 30 AND 31 THEN 'V,P,D,M,A' END,
D.DEPARTMENT_NAME,
REG.NAME,
C.LIMITED_TO_AOFFICE,C.LIMITED_TO_REGION,C.LIMITED_TO_OWNAGENCY,
C.DESIGNATION
FROM
(
SELECT A.DESIGNATION,A.AOFFICE,A.EMPLOYEEID,A.EMPLOYEE_NAME,B.SECURITYOPTIONID,B.SEC_GROUP_ID,B.SEC_GROUP,B.SECURITYOPTIONSUBNAME,A.LIMITED_TO_AOFFICE,A.LIMITED_TO_REGION,A.LIMITED_TO_OWNAGENCY,A.DEPARTMENTID,A.SECURITYREGIONID
FROM
(
SELECT EMP.DESIGNATION,EMP.AOFFICE,EMP.EMPLOYEEID,EMP.EMPLOYEE_NAME,EMP.LIMITED_TO_AOFFICE,EMP.LIMITED_TO_REGION,EMP.LIMITED_TO_OWNAGENCY,EMP.DEPARTMENTID,EMP.SECURITYREGIONID
FROM T_G_EMPLOYEES EMP
WHERE LEN(LTRIM(LTRIM(EMP.LOGIN)))>0
--AND EMP.EMPLOYEEID=202778
) AS A,
(
 SELECT SO.SECURITYOPTIONID,SG.SEC_GROUP_ID,SG.SEC_GROUP,SO.SECURITYOPTIONSUBNAME
FROM T_G_SECURITY_OPTION_GROUP SG WITH (NOLOCK)
INNER JOIN T_G_SECURITY_OPTIONS SO WITH (NOLOCK) ON SG.SEC_GROUP_ID=SO.SEC_GROUP_ID
) AS B) AS C
LEFT OUTER JOIN T_G_ACCESSLEVEL AL WITH (NOLOCK) ON AL.SECURITYOPTIONID=C.SECURITYOPTIONID AND AL.USER1A_ID=C.EMPLOYEEID
LEFT OUTER JOIN T_G_DEPARTMENT D WITH (NOLOCK) ON C.DEPARTMENTID=D.DEPARTMENTID
LEFT OUTER JOIN T_G_SECURITY_REGION REG  WITH (NOLOCK)  ON C.SECURITYREGIONID=REG.REGIONID
ORDER BY C.AOFFICE,C.EMPLOYEE_NAME,C.SEC_GROUP,C.SECURITYOPTIONSUBNAME


--Department
--1Aoffice
--Security Region
--Restricted to own  agency 
--Restricted to own  office

--SELECT TOP 10 * FROM T_G_EMPLOYEES
--SELECT TOP 10 * FROM T_G_DEPARTMENT D
--SELECT TOP 10 * FROM T_G_SECURITY_REGION
--
--SP_TABLES "%REGION%"A



select top 10 * from T_G_SECURITY_OPTIONS
order by 1