USE [AAMS]
GO

/****** Object:  View [dbo].[APROD_VW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[APROD_VW] AS
SELECT DATE,LCODE,OFFICEID,MONTH,YEAR, SUM(NETBOOKINGS) AS NETBOOKINGS FROM APROD WITH (NOLOCK)
GROUP BY MONTH,YEAR,DATE,LCODE,OFFICEID




GO

/****** Object:  View [dbo].[APROD_VW_NEW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[APROD_VW_NEW] AS  
SELECT DATE,LCODE,OFFICEID,[MONTH],[YEAR], NETBOOKINGS=SUM(NETBOOKINGS) FROM APROD WITH (NOLOCK)
GROUP BY MONTH,YEAR,DATE,LCODE,OFFICEID  

	UNION 

SELECT DATE,LCODE,OFFICEID=ISNULL(OFFICEID,''),[MONTH],[YEAR],SUM(NETBOOKINGS) FROM
(SELECT DATE=CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE)),T_C_TA_BOOKINGS.LCODE,OFFICEID,
[MONTH]=MONTH(CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE))),
[YEAR]=YEAR(CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE))),
NETBOOKINGS=0 FROM T_C_TA_BOOKINGS WITH (NOLOCK)
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=T_C_TA_BOOKINGS.LCODE) AS A
WHERE NOT EXISTS
	(
	  SELECT * FROM APROD WITH (NOLOCK)
	  WHERE
		APROD.LCODE=A.LCODE
		AND ISNULL(APROD.OFFICEID,'')=ISNULL(A.OFFICEID,'')
		AND APROD.MONTH= A.MONTH 
		AND APROD.YEAR = A.YEAR 
	)
GROUP BY DATE,LCODE,ISNULL(OFFICEID,''),[MONTH],[YEAR]

UNION 
SELECT DATE,LCODE,OFFICEID,[MONTH],[YEAR], NETBOOKINGS=0 FROM T_C_1A_BOOKINGS WITH (NOLOCK)
WHERE NOT EXISTS
	(
	  SELECT * FROM APROD WITH (NOLOCK)
	  WHERE
		APROD.LCODE=T_C_1A_BOOKINGS.LCODE
		AND ISNULL(APROD.OFFICEID,'')=ISNULL(T_C_1A_BOOKINGS.OFFICEID,'')
		AND APROD.MONTH= T_C_1A_BOOKINGS.MONTH 
		AND APROD.YEAR = T_C_1A_BOOKINGS.YEAR 
	)







GO

/****** Object:  View [dbo].[BIDT_AIR]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[BIDT_AIR] AS  
SELECT LCODE,OFFICEID,MONTH,YEAR,   
'MONTHYEAR'=(CAST(D1.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(D1.MONTH AS VARCHAR(2)) ,2) +'01'),  
'NETBOOKINGS' = SUM(NETBOOKINGS)  
FROM    
(   
 SELECT LCODE,OFFICEID,MONTH,YEAR,NETBOOKINGS=SUM(T_C_AIR_BOOKINGS.NETBOOKINGS)  
 FROM T_C_AIR_BOOKINGS  WITH (NOLOCK)   
 INNER JOIN LOCATION_MASTER ON T_C_AIR_BOOKINGS.LCODE = LOCATION_MASTER.LOCATION_CODE         
 --WHERE (CAST(T_C_AIR_BOOKINGS.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(T_C_AIR_BOOKINGS.MONTH AS VARCHAR(2)) ,2)) BETWEEN  @FROMDATE AND @TODATE   
 GROUP BY T_C_AIR_BOOKINGS.LCODE,OFFICEID,MONTH,YEAR   
 UNION ALL    
 SELECT APROD.LCODE,APROD.OFFICEID,APROD.MONTH,APROD.YEAR ,   
 NETBOOKINGS = T_C_1A_BOOKINGS.NETBOOKINGS-APROD.NETBOOKINGS  
 FROM  APROD  WITH (NOLOCK)   
 INNER JOIN LOCATION_MASTER ON APROD.LCODE = LOCATION_MASTER.LOCATION_CODE   
 INNER JOIN T_C_1A_BOOKINGS ON APROD.LCODE=T_C_1A_BOOKINGS.LCODE AND APROD.OFFICEID=T_C_1A_BOOKINGS.OFFICEID   
 AND APROD.MONTH=T_C_1A_BOOKINGS.MONTH  AND APROD.YEAR=T_C_1A_BOOKINGS.YEAR   
 WHERE    
 --(CAST(APROD.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(APROD.MONTH AS VARCHAR(2)) ,2)) BETWEEN  @FROMDATE AND @TODATE AND    
 APROD.NETBOOKINGS <> T_C_1A_BOOKINGS.NETBOOKINGS  ) AS D1    
 GROUP BY D1.LCODE,D1.OFFICEID,D1.MONTH,D1.YEAR ,(CAST(D1.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(D1.MONTH AS VARCHAR(2)) ,2))  
  
  
  
  



GO

/****** Object:  View [dbo].[BIDT_TEST]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[BIDT_TEST] AS  
  
SELECT B.LCODE,OFFICEID,B.DATE,B.AIR_NETBOOKINGS,B.CAR_NETBOOKINGS,B.HOTEL_NETBOOKINGS,B.INSURANCE_NETBOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE FROM  
  
(  
  
SELECT LCODE,OFFICEID,'DATE'=((AIR.YEAR*100)+AIR.MONTH)*100+1,AIR_NETBOOKINGS=AIR.NETBOOKINGS,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0 FROM T_C_AIR_BOOKINGS AIR WITH (NOLOCK)   
  
UNION ALL  
  
SELECT LCODE,OFFICEID,'DATE'=((CAR.YEAR*100)+CAR.MONTH)*100+1,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=CAR.NETBOOKINGS,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0 FROM T_C_CAR_BOOKINGS CAR WITH (NOLOCK)  
  
UNION ALL  
  
SELECT LCODE,OFFICEID,'DATE'=((HTL.YEAR*100)+HTL.MONTH)*100+1,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=HTL.NETBOOKINGS,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0 FROM T_C_HOTEL_BOOKINGS HTL WITH (NOLOCK)  
  
UNION ALL    
  
SELECT LCODE,OFFICEID,DATE,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE=0   
FROM(  

SELECT  INS.LCODE,VO.OFFICEID,INS.DATE,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=SUM(ISNULL(INS.TAS_BOOKINGS,0)),AIR_NETBOOKINGS_WITHOUTPASSIVE=0   
FROM T_C_TA_BOOKINGS INS  
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=INS.LCODE  
LEFT OUTER JOIN (SELECT  LCODE ,NETBOOKINGS=SUM(NETBOOKINGS) ,DATE1=((YEAR*100)+MONTH)*100+1 FROM APROD GROUP BY LCODE,MONTH,YEAR) AS APROD  
ON INS.LCODE = APROD.LCODE AND INS.DATE=APROD.DATE1  
WHERE VO.OFFICEID IS NOT NULL   
--AND INS.LCODE = 12098 AND INS.DATE  = 20080501  
GROUP BY INS.LCODE,VO.OFFICEID,INS.DATE



UNION  
--SELECT INS.* ,OFFICEID=APROD.OFFICEID1  FROM T_C_TA_BOOKINGS INS  
SELECT INS.LCODE,OFFICEID=APROD.OFFICEID1 ,INS.DATE,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=INS.TAS_BOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE=0   
FROM T_C_TA_BOOKINGS INS  
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=INS.LCODE  
INNER JOIN (  
SELECT A.DATE,DATE1=((A.YEAR*100)+A.MONTH)*100+1 ,A.LCODE,A.OFFICEID,A.MONTH,A.YEAR ,NETBOOKINGS=A.NETBOOKINGS ,OFFICEID1=B.OFFICEID  
FROM (SELECT * FROM APROD_VW_NEW WHERE ISNULL(OFFICEID,'') ='') A  
LEFT OUTER JOIN (SELECT * FROM APROD_VW_NEW WHERE ISNULL(OFFICEID,'') <>'') B ON A.LCODE =B.LCODE  AND A.MONTH = B.MONTH AND A.YEAR= B.YEAR  
) AS APROD  
ON INS.LCODE = APROD.LCODE AND INS.DATE=APROD.DATE1  
--WHERE INS.LCODE = 472 AND INS.DATE  = 20080101  
UNION  
SELECT LCODE,OFFICEID=ISNULL(OFFICEID,''),DATE=((YEAR*100)+MONTH)*100+1  ,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=SUM(NETBOOKINGS),AIR_NETBOOKINGS_WITHOUTPASSIVE=0  FROM    
(SELECT DATE=CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE)),T_C_TA_BOOKINGS.LCODE,OFFICEID,    
[MONTH]=MONTH(CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE))),    
[YEAR]=YEAR(CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE))),    
NETBOOKINGS=0 FROM T_C_TA_BOOKINGS WITH (NOLOCK)    
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=T_C_TA_BOOKINGS.LCODE) AS A    
WHERE NOT EXISTS    
 (    
   SELECT * FROM APROD WITH (NOLOCK)    
   WHERE    
  APROD.LCODE=A.LCODE    
  AND ISNULL(APROD.OFFICEID,'')=ISNULL(A.OFFICEID,'')    
  AND APROD.MONTH= A.MONTH     
  AND APROD.YEAR = A.YEAR     
 )    
GROUP BY DATE,LCODE,ISNULL(OFFICEID,''),[MONTH],[YEAR]    
) AS INSURANCE  

UNION ALL --AIRNET  
SELECT A.LCODE , A.OFFICEID,'DATE'=((A.YEAR*100)+A.MONTH)*100+1, AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,  
'AIR_NETBOOKINGS_WITHOUTPASSIVE' = SUM(ISNULL(A.NETBOOKINGS,0))   
FROM [VW_AIRNET] A WITH (NOLOCK)   
  
GROUP BY A.LCODE , A.OFFICEID, A.MONTH, A.YEAR   
  
) AS B  



GO

/****** Object:  View [dbo].[BIDT_TEST1]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


  
    
CREATE VIEW [dbo].[BIDT_TEST1] AS    
   
SELECT B.LCODE,OFFICEID,B.DATE,B.AIR,B.AIR_NETBOOKINGS,B.CAR_NETBOOKINGS,B.HOTEL_NETBOOKINGS,B.INSURANCE_NETBOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE FROM    
(    
  
SELECT LCODE,OFFICEID,'DATE'=((AIR.YEAR*100)+AIR.MONTH)*100+1,'AIR'=AIR.NETBOOKINGS,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0 FROM T_C_AIR_BOOKINGS AIR WITH (NOLOCK)   
  
UNION ALL  
  
SELECT LCODE,OFFICEID,DATE  = ((D1.YEAR*100)+D1.MONTH)*100+1, AIR=0,'AIR_NETBOOKINGS' = SUM(NETBOOKINGS),CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0  
FROM        
(       
 SELECT LCODE,OFFICEID,MONTH,YEAR,NETBOOKINGS=SUM(T_C_AIR_BOOKINGS.NETBOOKINGS)      
 FROM T_C_AIR_BOOKINGS  WITH (NOLOCK)       
 INNER JOIN LOCATION_MASTER ON T_C_AIR_BOOKINGS.LCODE = LOCATION_MASTER.LOCATION_CODE              
 GROUP BY T_C_AIR_BOOKINGS.LCODE,OFFICEID,MONTH,YEAR       
  
 UNION ALL        
  
 SELECT APROD.LCODE,APROD.OFFICEID,APROD.MONTH,APROD.YEAR ,       
 NETBOOKINGS = T_C_1A_BOOKINGS.NETBOOKINGS-APROD.NETBOOKINGS      
 FROM  APROD  WITH (NOLOCK)       
 INNER JOIN LOCATION_MASTER ON APROD.LCODE = LOCATION_MASTER.LOCATION_CODE       
 INNER JOIN T_C_1A_BOOKINGS ON APROD.LCODE=T_C_1A_BOOKINGS.LCODE AND APROD.OFFICEID=T_C_1A_BOOKINGS.OFFICEID       
 AND APROD.MONTH=T_C_1A_BOOKINGS.MONTH  AND APROD.YEAR=T_C_1A_BOOKINGS.YEAR       
 WHERE         
 APROD.NETBOOKINGS <> T_C_1A_BOOKINGS.NETBOOKINGS  ) AS D1        
 GROUP BY D1.LCODE,D1.OFFICEID,D1.MONTH,D1.YEAR ,(CAST(D1.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(D1.MONTH AS VARCHAR(2)) ,2))      
  
 UNION ALL    
    
 SELECT LCODE,OFFICEID,'DATE'=((CAR.YEAR*100)+CAR.MONTH)*100+1,'AIR'=0 ,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=CAR.NETBOOKINGS,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0 FROM T_C_CAR_BOOKINGS CAR WITH (NOLOCK)    
    
 UNION ALL    
    
 SELECT LCODE,OFFICEID,'DATE'=((HTL.YEAR*100)+HTL.MONTH)*100+1,'AIR'=0 ,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=HTL.NETBOOKINGS,INSURANCE_NETBOOKINGS=0,AIR_NETBOOKINGS_WITHOUTPASSIVE=0 FROM T_C_HOTEL_BOOKINGS HTL WITH (NOLOCK)    
    
 UNION ALL    
  
SELECT LCODE,OFFICEID,DATE,AIR =0,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE=0     
FROM(    

--SELECT  INS.LCODE,VO.OFFICEID,INS.DATE,'AIR'=0,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=INS.TAS_BOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE=0     
--FROM T_C_TA_BOOKINGS INS    
--LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=INS.LCODE    
--INNER JOIN (SELECT  *,DATE1=((YEAR*100)+MONTH)*100+1 FROM APROD) AS APROD    
--ON INS.LCODE = APROD.LCODE AND INS.DATE=APROD.DATE1    
--WHERE VO.OFFICEID IS NOT NULL     
----AND INS.LCODE = 472 AND INS.DATE  = 20080101    

SELECT  INS.LCODE,VO.OFFICEID,INS.DATE,'AIR'=0,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=SUM(ISNULL(INS.TAS_BOOKINGS,0)),AIR_NETBOOKINGS_WITHOUTPASSIVE=0     
FROM T_C_TA_BOOKINGS INS    
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=INS.LCODE    
LEFT OUTER JOIN (SELECT  LCODE ,NETBOOKINGS=SUM(NETBOOKINGS) ,DATE1=((YEAR*100)+MONTH)*100+1 FROM APROD GROUP BY LCODE,MONTH,YEAR) AS APROD    
ON INS.LCODE = APROD.LCODE AND INS.DATE=APROD.DATE1    
WHERE VO.OFFICEID IS NOT NULL     
--AND INS.LCODE = 12098 AND INS.DATE  = 20080501    
GROUP BY INS.LCODE,VO.OFFICEID,INS.DATE  

UNION    
  
--SELECT INS.* ,OFFICEID=APROD.OFFICEID1  FROM T_C_TA_BOOKINGS INS    
SELECT INS.LCODE,OFFICEID=APROD.OFFICEID1 ,INS.DATE,'AIR' = 0,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=INS.TAS_BOOKINGS,AIR_NETBOOKINGS_WITHOUTPASSIVE=0     
FROM T_C_TA_BOOKINGS INS    
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=INS.LCODE    
INNER JOIN (    
SELECT A.DATE,DATE1=((A.YEAR*100)+A.MONTH)*100+1 ,A.LCODE,A.OFFICEID,A.MONTH,A.YEAR ,NETBOOKINGS=A.NETBOOKINGS ,OFFICEID1=B.OFFICEID    
FROM (SELECT * FROM APROD_VW_NEW WHERE ISNULL(OFFICEID,'') ='') A    
LEFT OUTER JOIN (SELECT * FROM APROD_VW_NEW WHERE ISNULL(OFFICEID,'') <>'') B ON A.LCODE =B.LCODE  AND A.MONTH = B.MONTH AND A.YEAR= B.YEAR    
) AS APROD    
ON INS.LCODE = APROD.LCODE AND INS.DATE=APROD.DATE1    
--WHERE INS.LCODE = 472 AND INS.DATE  = 20080101    
UNION    
  
SELECT LCODE,OFFICEID=ISNULL(OFFICEID,''),DATE=((YEAR*100)+MONTH)*100+1 ,'AIR' = 0 ,AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=SUM(NETBOOKINGS),AIR_NETBOOKINGS_WITHOUTPASSIVE=0  FROM      
(SELECT DATE=CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE)),T_C_TA_BOOKINGS.LCODE,OFFICEID,      
[MONTH]=MONTH(CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE))),      
[YEAR]=YEAR(CONVERT(DATETIME,CONVERT(VARCHAR(12),DATE))),      
NETBOOKINGS=0 FROM T_C_TA_BOOKINGS WITH (NOLOCK)      
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON VO.LCODE=T_C_TA_BOOKINGS.LCODE) AS A      
WHERE NOT EXISTS      
 (      
   SELECT * FROM APROD WITH (NOLOCK)      
   WHERE      
  APROD.LCODE=A.LCODE      
  AND ISNULL(APROD.OFFICEID,'')=ISNULL(A.OFFICEID,'')      
  AND APROD.MONTH= A.MONTH       
  AND APROD.YEAR = A.YEAR       
 )      
GROUP BY DATE,LCODE,ISNULL(OFFICEID,''),[MONTH],[YEAR]      
) AS INSURANCE    
  
UNION ALL --AIRNET    
  
SELECT A.LCODE , A.OFFICEID,'DATE'=((A.YEAR*100)+A.MONTH)*100+1,'AIR'=0 , AIR_NETBOOKINGS=0,CAR_NETBOOKINGS=0,HOTEL_NETBOOKINGS=0,INSURANCE_NETBOOKINGS=0,    
'AIR_NETBOOKINGS_WITHOUTPASSIVE' = SUM(ISNULL(A.NETBOOKINGS,0))     
FROM [VW_AIRNET] A WITH (NOLOCK)     
    
GROUP BY A.LCODE , A.OFFICEID, A.MONTH, A.YEAR     
    
) AS B    
    
  


GO

/****** Object:  View [dbo].[T_C_1A_DAILY_BOOKINGS_VW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE  VIEW [dbo].[T_C_1A_DAILY_BOOKINGS_VW] AS  
SELECT  Lcode,Month,Year,SUM(D1) AS D1,SUM(D2) AS D2,SUM(D3) AS D3,SUM(D4) AS D4,SUM(D5) AS D5,SUM(D6) AS D6,SUM(D7) AS D7,SUM(D8) AS D8,SUM(D9) AS D9,SUM(D10) AS D10,SUM(D11) AS D11,SUM(D12) AS D12,SUM(D13) AS D13,SUM(D14) AS D14,SUM(D15) AS D15,SUM(D16) AS D16,SUM(D17) AS D17,SUM(D18) AS D18,SUM(D19) AS D19,SUM(D20) AS D20,SUM(D21) AS D21,SUM(D22) AS D22,SUM(D23) AS D23,SUM(D24) AS D24,SUM(D25) AS D25,SUM(D26) AS D26,SUM(D27) AS D27,SUM(D28) AS D28,SUM(D29) AS D29,SUM(D30) AS D30,SUM(D31) AS D31,SUM(AverageBookings) AS AverageBookings,SUM(Netbookings) AS Netbookings 
FROM T_C_1A_DAILY_BOOKINGS WITH (NOLOCK)  
GROUP BY LCODE,MONTH,YEAR  







GO

/****** Object:  View [dbo].[T_C_1A_DAILY_BOOKINGS2_VW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO



CREATE VIEW [dbo].[T_C_1A_DAILY_BOOKINGS2_VW] AS 
SELECT [DATE],LCODE,SUM(AIR_ADD_BOOKINGS) AS AIR_ADD_BOOKINGS,SUM(AIR_CANCEL_BOOKINGS) AS AIR_CANCEL_BOOKINGS,
SUM(AIR_MODIFY_BOOKINGS) AS AIR_MODIFY_BOOKINGS,SUM(AIR_NET_BOOKINGS) AS AIR_NET_BOOKINGS,SUM(PASSIVE_ADD) AS PASSIVE_ADD,
SUM(PASSIVE_CANCEL) AS PASSIVE_CANCEL,SUM(PASSIVE_MODIFY) AS PASSIVE_MODIFY,SUM(PASSIVE_NET) AS PASSIVE_NET,SUM(NETBOOKINGS) AS NETBOOKINGS,' ' AS AIRLINE_CODE
FROM T_C_1A_DAILY_BOOKINGS2 WITH (NOLOCK)
GROUP BY [DATE],LCODE




GO

/****** Object:  View [dbo].[T_C_1A_DAILY_BOOKINGS3_VW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[T_C_1A_DAILY_BOOKINGS3_VW] AS
SELECT LCode,Date,'Car_Bookings'=SUM(ISNULL(Car_Bookings,0)),'Hotel_Bookings'=SUM(ISNULL(Hotel_Bookings,0)),'Car_Voucher_Printed'=SUM(ISNULL(Car_Voucher_Printed,0)),'Car_Number_of_Days'=SUM(ISNULL(Car_Number_of_Days,0)),'Hotel_Nights'=SUM(ISNULL(Hotel_Nights,0)) FROM T_C_1A_DAILY_BOOKINGS3
GROUP BY LCode,Date




GO

/****** Object:  View [dbo].[T_C_1A_DAILY_PB_BOOKINGS_VW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE    VIEW [dbo].[T_C_1A_DAILY_PB_BOOKINGS_VW] AS  
SELECT  Lcode,Month,Year,SUM(D1) AS D1,SUM(D2) AS D2,SUM(D3) AS D3,SUM(D4) AS D4,SUM(D5) AS D5,SUM(D6) AS D6,SUM(D7) AS D7,SUM(D8) AS D8,SUM(D9) AS D9,SUM(D10) AS D10,SUM(D11) AS D11,SUM(D12) AS D12,SUM(D13) AS D13,SUM(D14) AS D14,SUM(D15) AS D15,SUM(D16) AS D16,SUM(D17) AS D17,SUM(D18) AS D18,SUM(D19) AS D19,SUM(D20) AS D20,SUM(D21) AS D21,SUM(D22) AS D22,SUM(D23) AS D23,SUM(D24) AS D24,SUM(D25) AS D25,SUM(D26) AS D26,SUM(D27) AS D27,SUM(D28) AS D28,SUM(D29) AS D29,SUM(D30) AS D30,SUM(D31) AS D31,
SUM(ISNULL(AverageBookings,0)) AS AverageBookings,
SUM(ISNULL(Netbookings,0)) AS Netbookings 
FROM T_C_1A_DAILY_PB_BOOKINGS WITH (NOLOCK)  GROUP BY LCODE,MONTH,YEAR  








GO

/****** Object:  View [dbo].[T_C_1A_DAILY_PB_BOOKINGS2_VW]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO



CREATE VIEW [dbo].[T_C_1A_DAILY_PB_BOOKINGS2_VW] AS 
SELECT [DATE],LCODE,SUM(AIR_ADD_BOOKINGS) AS AIR_ADD_BOOKINGS,SUM(AIR_CANCEL_BOOKINGS) AS AIR_CANCEL_BOOKINGS,
SUM(AIR_MODIFY_BOOKINGS) AS AIR_MODIFY_BOOKINGS,SUM(AIR_NET_BOOKINGS) AS AIR_NET_BOOKINGS,SUM(PASSIVE_ADD) AS PASSIVE_ADD,
SUM(PASSIVE_CANCEL) AS PASSIVE_CANCEL,SUM(PASSIVE_MODIFY) AS PASSIVE_MODIFY,SUM(PASSIVE_NET) AS PASSIVE_NET,SUM(NETBOOKINGS) AS NETBOOKINGS,' ' AS AIRLINE_CODE
FROM T_C_1A_DAILY_PB_BOOKINGS2 WITH (NOLOCK)
GROUP BY [DATE],LCODE







GO

/****** Object:  View [dbo].[V_BR_LOCATION_CODE]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_BR_LOCATION_CODE]

AS

SELECT ALLLOCATION.*
FROM 
(SELECT 'LOCATION_CODE1'=LOCATION_CODE, 'CHAIN_CODE1'=CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM BR_LOCATION_MASTER WITH(NOLOCK), 
(
	SELECT SUP.EMPLOYEEID,'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME , EMP.GROUPTYPEID
	FROM T_G_EMPLOYEES EMP WITH(NOLOCK) , T_G_EMPLOYEES SUP WITH(NOLOCK) 
	WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND isnull(SUP.Show_Prod_ISUPERVISOR,0)=1

	UNION 
	SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, LIMITED_TO_OWNAGENCY, LIMITED_TO_REGION, LIMITED_TO_AOFFICE, SECURITYREGIONID, EMPLOYEE_NAME, GROUPTYPEID
	FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE BR_LOCATION_MASTER.RESP_1A=TBL.EMPLOYEEID
AND LIMITED_TO_OWNAGENCY=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM BR_LOCATION_MASTER WITH(NOLOCK), 
	(
		SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME,  EMP.GROUPTYPEID
		FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP WITH(NOLOCK)
			WHERE EMP.EMPLOYEEID=SUP.IMMEDIATESUPERVISORID AND SUP.Show_Prod_ISUPERVISOR=1
		UNION 
		SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice,securityregionid, employee_name,  GROUPTYPEID
	    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE BR_LOCATION_MASTER.AOFFICE=TBL.AOFFICE
AND TBL.LIMITED_TO_AOFFICE=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM BR_LOCATION_MASTER WITH(NOLOCK),T_G_SECURITY_REGION_AOFFICE WITH(NOLOCK), 
	(
	  SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.Limited_To_OwnAgency, SUP.Limited_To_Region, SUP.Limited_To_Aoffice, SUP.securityregionid, sup.employee_name ,  EMP.GROUPTYPEID
	  FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP  WITH(NOLOCK)
	  WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND SUP.Show_Prod_ISUPERVISOR=1
	  UNION 
     SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice, securityregionid, employee_name,  GROUPTYPEID
    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE TBL.securityregionid=T_G_SECURITY_REGION_AOFFICE.regionid
and BR_LOCATION_MASTER.AOFFICE=T_G_SECURITY_REGION_AOFFICE.AOFFICE
AND LIMITED_TO_region=1
) AS ALLLOCATION, AGROUP
WHERE ALLLOCATION.CHAIN_CODE1=AGROUP.CHAIN_CODE
AND (ALLLOCATION.GROUPTYPEID IS NULL OR ALLLOCATION.GROUPTYPEID=AGROUP.GROUPTYPEID)




GO

/****** Object:  View [dbo].[V_COURSESESSION]    Script Date: 04/28/2011 15:42:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_COURSESESSION]
AS 

SELECT TR_COURSES_ID,TR_COURSES_REQ_CONFIG,EMPLOYEE_ID1,EMPLOYEE_ID2,TR_COURSES_NBPART,TR_COURSES_EXPECT_DATE,TR_CLOCATION_ID,
TR_COURSE_ID,TR_COURSES_START_TIME,TR_COURSES_END_DATE,TR_COURSES_END_TIME,INTERNAL 
FROM T_TR_COURSE_SESSION  WITH(NOLOCK)
LEFT OUTER JOIN T_G_EMPLOYEES WITH (NOLOCK) ON T_TR_COURSE_SESSION.EMPLOYEE_ID1 = T_G_EMPLOYEES.EMPLOYEEID
UNION 
SELECT TR_COURSES_ID,TR_COURSES_REQ_CONFIG,EMPLOYEE_ID1,EMPLOYEE_ID2,TR_COURSES_NBPART,TR_COURSES_EXPECT_DATE,TR_CLOCATION_ID,
TR_COURSE_ID,TR_COURSES_START_TIME,TR_COURSES_END_DATE,TR_COURSES_END_TIME,INTERNAL 
FROM T_TR_COURSE_SESSION  WITH(NOLOCK)
LEFT OUTER JOIN T_G_EMPLOYEES WITH (NOLOCK) ON T_TR_COURSE_SESSION.EMPLOYEE_ID2 = T_G_EMPLOYEES.EMPLOYEEID


GO

/****** Object:  View [dbo].[V_CURRENT_OFFICEIDS]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_CURRENT_OFFICEIDS]  
AS
SELECT LCODE, OFFICEID  
FROM CRSUSE WITH (NOLOCK)  
WHERE CURRENTID = 'Y' AND CRS = '1A'

GO

/****** Object:  View [dbo].[V_LOCATION_CODE]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_LOCATION_CODE]

AS

SELECT ALLLOCATION.*
FROM 
(SELECT 'LOCATION_CODE1'=LOCATION_CODE, 'CHAIN_CODE1'=CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK), 
(
	SELECT SUP.EMPLOYEEID,'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME , EMP.GROUPTYPEID
	FROM T_G_EMPLOYEES EMP WITH(NOLOCK) , T_G_EMPLOYEES SUP WITH(NOLOCK) 
	WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND isnull(SUP.Show_Prod_ISUPERVISOR,0)=1

	UNION 
	SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, LIMITED_TO_OWNAGENCY, LIMITED_TO_REGION, LIMITED_TO_AOFFICE, SECURITYREGIONID, EMPLOYEE_NAME, GROUPTYPEID
	FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE LOCATION_MASTER.RESP_1A=TBL.EMPLOYEEID
AND LIMITED_TO_OWNAGENCY=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK), 
	(
		SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME,  EMP.GROUPTYPEID
		FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP WITH(NOLOCK)
			WHERE EMP.EMPLOYEEID=SUP.IMMEDIATESUPERVISORID AND SUP.Show_Prod_ISUPERVISOR=1
		UNION 
		SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice,securityregionid, employee_name,  GROUPTYPEID
	    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE LOCATION_MASTER.AOFFICE=TBL.AOFFICE
AND TBL.LIMITED_TO_AOFFICE=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK),T_G_SECURITY_REGION_AOFFICE WITH(NOLOCK), 
	(
	  SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.Limited_To_OwnAgency, SUP.Limited_To_Region, SUP.Limited_To_Aoffice, SUP.securityregionid, sup.employee_name ,  EMP.GROUPTYPEID
	  FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP  WITH(NOLOCK)
	  WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND SUP.Show_Prod_ISUPERVISOR=1
	  UNION 
     SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice, securityregionid, employee_name,  GROUPTYPEID
    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE TBL.securityregionid=T_G_SECURITY_REGION_AOFFICE.regionid
and LOCATION_MASTER.AOFFICE=T_G_SECURITY_REGION_AOFFICE.AOFFICE
AND LIMITED_TO_region=1
) AS ALLLOCATION, AGROUP WITH (NOLOCK)
WHERE ALLLOCATION.CHAIN_CODE1=AGROUP.CHAIN_CODE
AND (ALLLOCATION.GROUPTYPEID IS NULL OR ALLLOCATION.GROUPTYPEID=AGROUP.GROUPTYPEID)



GO

/****** Object:  View [dbo].[V_LOCATION_CODE_BACK]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_LOCATION_CODE_BACK]

AS

SELECT ALLLOCATION.*
FROM 
(SELECT 'LOCATION_CODE1'=LOCATION_CODE, 'CHAIN_CODE1'=CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK), 
(
	SELECT SUP.EMPLOYEEID,'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME , EMP.GROUPTYPEID
	FROM T_G_EMPLOYEES EMP WITH(NOLOCK) , T_G_EMPLOYEES SUP WITH(NOLOCK) 
	WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND isnull(SUP.Show_Prod_ISUPERVISOR,0)=1

	UNION 
	SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, LIMITED_TO_OWNAGENCY, LIMITED_TO_REGION, LIMITED_TO_AOFFICE, SECURITYREGIONID, EMPLOYEE_NAME, GROUPTYPEID
	FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE LOCATION_MASTER.RESP_1A=TBL.EMPLOYEEID
AND LIMITED_TO_OWNAGENCY=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK), 
	(
		SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME,  EMP.GROUPTYPEID
		FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP WITH(NOLOCK)
			WHERE EMP.EMPLOYEEID=SUP.IMMEDIATESUPERVISORID AND SUP.Show_Prod_ISUPERVISOR=1
		UNION 
		SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice,securityregionid, employee_name,  GROUPTYPEID
	    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE LOCATION_MASTER.AOFFICE=TBL.AOFFICE
AND TBL.LIMITED_TO_AOFFICE=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK),T_G_SECURITY_REGION_AOFFICE WITH(NOLOCK), 
	(
	  SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.Limited_To_OwnAgency, SUP.Limited_To_Region, SUP.Limited_To_Aoffice, SUP.securityregionid, sup.employee_name ,  EMP.GROUPTYPEID
	  FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP  WITH(NOLOCK)
	  WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND SUP.Show_Prod_ISUPERVISOR=1
	  UNION 
     SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice, securityregionid, employee_name,  GROUPTYPEID
    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE TBL.securityregionid=T_G_SECURITY_REGION_AOFFICE.regionid
and LOCATION_MASTER.AOFFICE=T_G_SECURITY_REGION_AOFFICE.AOFFICE
AND LIMITED_TO_region=1
) AS ALLLOCATION, AGROUP
WHERE ALLLOCATION.CHAIN_CODE1=AGROUP.CHAIN_CODE
AND (ALLLOCATION.GROUPTYPEID IS NULL OR ALLLOCATION.GROUPTYPEID=AGROUP.GROUPTYPEID)



GO

/****** Object:  View [dbo].[V_LOCATION_CODE_WB]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[V_LOCATION_CODE_WB]
AS

SELECT ALLLOCATION.*
FROM 
(SELECT 'LOCATION_CODE1'=LOCATION_CODE, 'CHAIN_CODE1'=CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK), 
(
	SELECT SUP.EMPLOYEEID,'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME , EMP.GROUPTYPEID
	FROM T_G_EMPLOYEES EMP WITH(NOLOCK) , T_G_EMPLOYEES SUP WITH(NOLOCK) 
	WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND isnull(SUP.Show_Prod_ISUPERVISOR,0)=1

	UNION 
	SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, LIMITED_TO_OWNAGENCY, LIMITED_TO_REGION, LIMITED_TO_AOFFICE, SECURITYREGIONID, EMPLOYEE_NAME, GROUPTYPEID
	FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE LOCATION_MASTER.RESP_1A=TBL.EMPLOYEEID
AND LIMITED_TO_OWNAGENCY=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK), 
	(
		SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.LIMITED_TO_OWNAGENCY, SUP.LIMITED_TO_REGION, SUP.LIMITED_TO_AOFFICE, SUP.SECURITYREGIONID, SUP.EMPLOYEE_NAME,  EMP.GROUPTYPEID
		FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP WITH(NOLOCK)
			WHERE EMP.EMPLOYEEID=SUP.IMMEDIATESUPERVISORID AND SUP.Show_Prod_ISUPERVISOR=1
		UNION 
		SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice,securityregionid, employee_name,  GROUPTYPEID
	    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE LOCATION_MASTER.AOFFICE=TBL.AOFFICE
AND TBL.LIMITED_TO_AOFFICE=1

union

SELECT LOCATION_CODE, CHAIN_CODE, TBL.EMPLOYEEID1, GROUPTYPEID
FROM LOCATION_MASTER WITH(NOLOCK),T_G_SECURITY_REGION_AOFFICE WITH(NOLOCK), 
	(
	  SELECT SUP.EMPLOYEEID, 'EMPLOYEEID1'=EMP.EMPLOYEEID, SUP.AOFFICE, SUP.Limited_To_OwnAgency, SUP.Limited_To_Region, SUP.Limited_To_Aoffice, SUP.securityregionid, sup.employee_name ,  EMP.GROUPTYPEID
	  FROM T_G_EMPLOYEES EMP WITH(NOLOCK), T_G_EMPLOYEES SUP  WITH(NOLOCK)
	  WHERE EMP.EMPLOYEEID=SUP.ImmediateSupervisorID AND SUP.Show_Prod_ISUPERVISOR=1
	  UNION 
     SELECT EMPLOYEEID, 'EMPLOYEEID1'=EMPLOYEEID, AOFFICE, Limited_To_OwnAgency, Limited_To_Region, Limited_To_Aoffice, securityregionid, employee_name,  GROUPTYPEID
    FROM T_G_EMPLOYEES WITH(NOLOCK)) AS TBL
WHERE TBL.securityregionid=T_G_SECURITY_REGION_AOFFICE.regionid
and LOCATION_MASTER.AOFFICE=T_G_SECURITY_REGION_AOFFICE.AOFFICE
AND LIMITED_TO_region=1
) AS ALLLOCATION, AGROUP WITH (NOLOCK)
WHERE ALLLOCATION.CHAIN_CODE1=AGROUP.CHAIN_CODE
--AND (ALLLOCATION.GROUPTYPEID IS NULL OR ALLLOCATION.GROUPTYPEID=AGROUP.GROUPTYPEID)




GO

/****** Object:  View [dbo].[v_midtview2]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO


CREATE VIEW [dbo].[v_midtview2]
AS
SELECT T_MIDTPRODUCTIVITY_AIR.LCODE, 
    T_MIDTPRODUCTIVITY_AIR.CRSCODE, 
    SUM(T_MIDTPRODUCTIVITY_AIR.netbookings) AS totp, 
    T_AIRLINE.Name AS airline_name, 
    T_MIDTPRODUCTIVITY_AIR.YEAR, 
    T_MIDTPRODUCTIVITY_AIR.MONTH, 
    T_MIDTPRODUCTIVITY_AIR.DATE AS CDATE
FROM T_MIDTPRODUCTIVITY_AIR   WITH (NOLOCK) INNER JOIN
    T_AIRLINE  WITH (NOLOCK)  ON 
    T_MIDTPRODUCTIVITY_AIR.AIRLINE_CODE = T_AIRLINE.AIRLINE_CODE
GROUP BY T_MIDTPRODUCTIVITY_AIR.LCODE, 
    T_MIDTPRODUCTIVITY_AIR.DATE, 
    T_MIDTPRODUCTIVITY_AIR.YEAR, 
    T_MIDTPRODUCTIVITY_AIR.MONTH, 
    T_MIDTPRODUCTIVITY_AIR.CRSCODE, T_AIRLINE.Name



GO

/****** Object:  View [dbo].[v_password]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[v_password] AS SELECT DISTINCT MAX(CASE br_id WHEN '1' THEN region ELSE NULL END) AS [1], MAX(CASE br_id WHEN '2' THEN region ELSE NULL END) AS [2], MAX(CASE br_id WHEN '3' THEN region ELSE NULL END) AS [3], MAX(CASE br_id WHEN '4' THEN region ELSE NULL END) AS [4], MAX(CASE br_id WHEN '5' THEN region ELSE NULL END) AS [5], MAX(CASE br_id WHEN '6' THEN region ELSE NULL END) AS [6], MAX(CASE br_id WHEN '7' THEN region ELSE NULL END) AS [7], MAX(CASE br_id WHEN '8' THEN region ELSE NULL END) AS [8], MAX(CASE br_id WHEN '9' THEN region ELSE NULL END) AS [9], MAX(CASE br_id WHEN '10' THEN region ELSE NULL END) AS [10], MAX(CASE br_id WHEN '11' THEN region ELSE NULL END) AS [11], MAX(CASE br_id WHEN '12' THEN region ELSE NULL END) AS [12], MAX(CASE br_id WHEN '13' THEN region ELSE NULL END) AS [13], MAX(CASE br_id WHEN '14' THEN region ELSE NULL END) AS [14], MAX(CASE br_id WHEN '15' THEN region ELSE NULL END) AS [15], MAX(CASE br_id WHEN '16' THEN region ELSE NULL END) AS [16], MAX(CASE br_id WHEN '17' THEN region ELSE NULL END) AS [17], MAX(CASE br_id WHEN '18' THEN region ELSE NULL END) AS [18], MAX(CASE br_id WHEN '19' THEN region ELSE NULL END) AS [19], MAX(CASE br_id WHEN '20' THEN region ELSE NULL END) AS [20], MAX(CASE br_id WHEN '21' THEN region ELSE NULL END) AS [21], MAX(CASE br_id WHEN '22' THEN region ELSE NULL END) AS [22], MAX(CASE br_id WHEN '23' THEN region ELSE NULL END) AS [23], MAX(CASE br_id WHEN '24' THEN region ELSE NULL END) AS [24], MAX(CASE br_id WHEN '25' THEN region ELSE NULL END) AS [25], MAX(CASE br_id WHEN '26' THEN region ELSE NULL END) AS [26], MAX(CASE br_id WHEN '27' THEN region ELSE NULL END) AS [27], MAX(CASE br_id WHEN '28' THEN region ELSE NULL END) AS [28], MAX(CASE br_id WHEN '160' THEN region ELSE NULL END) AS [160], MAX(CASE br_id WHEN '161' THEN region ELSE NULL END) AS [161], MAX(CASE br_id WHEN '162' THEN region ELSE NULL END) AS [162], MAX(CASE br_id WHEN '163' THEN region ELSE NULL END) AS [163], MAX(CASE br_id WHEN '164' THEN region ELSE NULL END) AS [164], MAX(CASE br_id WHEN '165' THEN region ELSE NULL END) AS [165], MAX(CASE br_id WHEN '166' THEN region ELSE NULL END) AS [166], MAX(CASE br_id WHEN '167' THEN region ELSE NULL END) AS [167], MAX(CASE br_id WHEN '168' THEN region ELSE NULL END) AS [168], MAX(CASE br_id WHEN '169' THEN region ELSE NULL END) AS [169], MAX(CASE br_id WHEN '170' THEN region ELSE NULL END) AS [170], MAX(CASE br_id WHEN '171' THEN region ELSE NULL END) AS [171] FROM branch
GO

/****** Object:  View [dbo].[V_TEST]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW 
[dbo].[V_TEST]
AS
SELECT  TR_COURSE_ID,TEST_TIME,NO_OF_QUESTIONS FROM T_MS_TEST_MASTER

GO

/****** Object:  View [dbo].[VW_1A_AIRLINE_TKT_BOOKINGS]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_1A_AIRLINE_TKT_BOOKINGS] AS 
--DAILYBOOKINGS
SELECT T.LCODE,T.OFFICEID,
SUBSTRING(CAST(DATE AS VARCHAR),5,2) AS [MONTH],LEFT(DATE,4) AS [YEAR],[DATE],AIRLINE_CODE,
[TKT_NETBOOKINGS]=ISS_E_TKT,0 AS DB_NETBOOKINGS,0 AS [1A_NETBOOKINGS],0 AS MT_NETBOOKINGS 
FROM 	T_C_1A_TICKET_BOOKINGS T WITH(NOLOCK)
	UNION ALL
SELECT DB.LCODE,VO.OFFICEID,MONTH,YEAR,[DATE]=(([YEAR]*100)+[MONTH])*100+1,AIRLINE_CODE, 
0 AS [TKT_NETBOOKINGS],NETBOOKINGS AS DB_NETBOOKINGS,0 AS [1A_NETBOOKINGS],0 AS MT_NETBOOKINGS
FROM T_C_1A_DAILY_BOOKINGS DB WITH(NOLOCK)
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON DB.LCODE=VO.LCODE
	UNION ALL
--MIDT
SELECT DB.LCODE,VO.OFFICEID,MONTH,YEAR,[DATE]=(([YEAR]*100)+[MONTH])*100+1,AIRLINE_CODE,
0 AS [TKT_NETBOOKINGS],0 AS DB_NETBOOKINGS,0 AS [1A_NETBOOKINGS],NETBOOKINGS AS MT_NETBOOKINGS FROM T_MIDTPRODUCTIVITY_AIR DB WITH(NOLOCK)
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON DB.LCODE=VO.LCODE






GO

/****** Object:  View [dbo].[VW_1A_TKT_BOOKINGS]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VW_1A_TKT_BOOKINGS] AS 
--DAILYBOOKINGS
SELECT T.LCODE,T.OFFICEID,
SUBSTRING(CAST(DATE AS VARCHAR),5,2) AS [MONTH],LEFT(DATE,4) AS [YEAR],[DATE],
	[TKT_NETBOOKINGS]=ISS_E_TKT,
	0 AS DB_NETBOOKINGS,
	0 AS [1A_NETBOOKINGS],
	0 AS MT_NETBOOKINGS, 
	0 AS CODD,
	0 AS HX_BOOKINGS
FROM 	T_C_1A_TICKET_BOOKINGS T WITH(NOLOCK)
--WHERE [DATE] BETWEEN 20100401 AND 20100431
--GROUP BY T.LCODE,T.OFFICEID,[DATE]
	UNION ALL
SELECT DB.LCODE,VO.OFFICEID,MONTH,YEAR,[DATE]=(([YEAR]*100)+[MONTH])*100+1, 
	0 AS [TKT_NETBOOKINGS],
	NETBOOKINGS AS DB_NETBOOKINGS,
	0 AS [1A_NETBOOKINGS],
	0 AS MT_NETBOOKINGS,
	0 AS CODD,
	0 AS HX_BOOKINGS
FROM T_C_1A_DAILY_BOOKINGS DB WITH(NOLOCK)
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON DB.LCODE=VO.LCODE
--WHERE (([YEAR]*100)+[MONTH])*100+1 BETWEEN 20100401 AND 20100431
--GROUP BY DB.LCODE,VO.OFFICEID,(([YEAR]*100)+[MONTH])*100+1
	UNION ALL
--BIDT
SELECT LCODE,OFFICEID,MONTH,YEAR,[DATE]=(([YEAR]*100)+[MONTH])*100+1,
	0 AS [TKT_NETBOOKINGS],
	0 AS DB_NETBOOKINGS,
	NETBOOKINGS AS [1A_NETBOOKINGS],
	0 AS MT_NETBOOKINGS,
	0 AS CODD,
	0 AS HX_BOOKINGS
FROM T_C_AIR_BOOKINGS  WITH(NOLOCK)
WHERE ACCESS_LEVEL<>'PB'
--AND (([YEAR]*100)+[MONTH])*100+1 BETWEEN 20100401 AND 20100431
--GROUP BY LCODE,OFFICEID,(([YEAR]*100)+[MONTH])*100+1
	UNION ALL
--MIDT
SELECT DB.LCODE,VO.OFFICEID,MONTH,YEAR,[DATE]=(([YEAR]*100)+[MONTH])*100+1,
	0 AS [TKT_NETBOOKINGS],
	0 AS DB_NETBOOKINGS,
	0 AS [1A_NETBOOKINGS],
	NETBOOKINGS AS MT_NETBOOKINGS, 
	0 AS CODD,
	0 AS HX_BOOKINGS
FROM T_MIDTPRODUCTIVITY_AIR DB WITH(NOLOCK)
LEFT OUTER JOIN V_CURRENT_OFFICEIDS VO ON DB.LCODE=VO.LCODE
--WHERE (([YEAR]*100)+[MONTH])*100+1 BETWEEN 20100401 AND 20100431
--GROUP BY DB.LCODE,VO.OFFICEID,(([YEAR]*100)+[MONTH])*100+1
	UNION ALL
SELECT 
	LCODE,OFFICEID,MONTH,YEAR,[DATE]=(([YEAR]*100)+[MONTH])*100+1,
	0 AS [TKT_NETBOOKINGS],
	0 AS DB_NETBOOKINGS,
	0 AS [1A_NETBOOKINGS],0 AS MT_NETBOOKINGS,
	CODD,
	HX_BOOKINGS
FROM T_INC_NIDT_PRODUCTIVITY_EXPORTED WITH(NOLOCK)							



GO

/****** Object:  View [dbo].[VW_AIR_CAR_HOTEL]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_AIR_CAR_HOTEL] AS
SELECT [DATE],LCODE,SUM(AIR_ADD_BOOKINGS) AS AIR_ADD_BOOKINGS,SUM(AIR_CANCEL_BOOKINGS) AS AIR_CANCEL_BOOKINGS,  
SUM(AIR_MODIFY_BOOKINGS) AS AIR_MODIFY_BOOKINGS,SUM(AIR_NET_BOOKINGS) AS AIR_NET_BOOKINGS,SUM(PASSIVE_ADD) AS PASSIVE_ADD,  
SUM(PASSIVE_CANCEL) AS PASSIVE_CANCEL,SUM(PASSIVE_MODIFY) AS PASSIVE_MODIFY,SUM(PASSIVE_NET) AS PASSIVE_NET,
SUM(AIR_NETBOOKINGS) AS NETBOOKINGS,SUM(CAR_BOOKINGS) AS CAR_BOOKINGS,SUM(HOTEL_BOOKINGS) AS HOTEL_BOOKINGS
FROM
(
SELECT 
DATE,LCODE,AIR_ADD_BOOKINGS,AIR_CANCEL_BOOKINGS,AIR_MODIFY_BOOKINGS,AIR_NET_BOOKINGS,PASSIVE_ADD,PASSIVE_CANCEL,PASSIVE_MODIFY,PASSIVE_NET,NETBOOKINGS AS AIR_NETBOOKINGS,
0 AS CAR_BOOKINGS,0 AS HOTEL_BOOKINGS
FROM T_C_1A_DAILY_BOOKINGS2 WITH (NOLOCK)  
UNION ALL
SELECT DATE,LCODE,0 AS AIR_ADD_BOOKINGS,0 AS AIR_CANCEL_BOOKINGS,0 AS AIR_MODIFY_BOOKINGS,0 AS AIR_NET_BOOKINGS,0 AS PASSIVE_ADD,0 AS PASSIVE_CANCEL,0 AS PASSIVE_MODIFY,0 AS PASSIVE_NET,0 AS AIR_NETBOOKINGS,CAR_BOOKINGS,HOTEL_BOOKINGS
FROM T_C_1A_DAILY_BOOKINGS3 WITH (NOLOCK)
) AS A
GROUP BY LCODE,DATE





  
  

GO

/****** Object:  View [dbo].[VW_AIR_CAR_HOTEL_CITYREPORT]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_AIR_CAR_HOTEL_CITYREPORT] AS
SELECT LCODE,[MONTH],[YEAR],D1=SUM(D1),D2=SUM(D2),D3=SUM(D3),D4=SUM(D4),D5=SUM(D5),D6=SUM(D6),D7=SUM(D7),D8=SUM(D8),D9=SUM(D9),D10=SUM(D10),D11=SUM(D11),D12=SUM(D12),D13=SUM(D13),D14=SUM(D14),D15=SUM(D15),D16=SUM(D16),D17=SUM(D17),D18=SUM(D18),D19=SUM(D19),D20=SUM(D20),D21=SUM(D21),D22=SUM(D22),D23=SUM(D23),D24=SUM(D24),D25=SUM(D25),D26=SUM(D26),D27=SUM(D27),D28=SUM(D28),D29=SUM(D29),D30=SUM(D30),D31=SUM(D31),NETBOOKINGS=SUM(NETBOOKINGS) FROM(
SELECT 
	LCODE,[MONTH],[YEAR],
	D1=SUM(D1),
	D2=SUM(D2),
	D3=SUM(D3),
	D4=SUM(D4),
	D5=SUM(D5),
	D6=SUM(D6),
	D7=SUM(D7),
	D8=SUM(D8),
	D9=SUM(D9),
	D10=SUM(D10),
	D11=SUM(D11),
	D12=SUM(D12),
	D13=SUM(D13),
	D14=SUM(D14),
	D15=SUM(D15),
	D16=SUM(D16),
	D17=SUM(D17),
	D18=SUM(D18),
	D19=SUM(D19),
	D20=SUM(D20),
	D21=SUM(D21),
	D22=SUM(D22),
	D23=SUM(D23),
	D24=SUM(D24),
	D25=SUM(D25),
	D26=SUM(D26),
	D27=SUM(D27),
	D28=SUM(D28),
	D29=SUM(D29),
	D30=SUM(D30),
	D31=SUM(D31),
	NETBOOKINGS=SUM(NETBOOKINGS)
FROM
	T_C_1A_DAILY_BOOKINGS WITH(NOLOCK)
GROUP BY 
LCODE,[MONTH],[YEAR]

UNION ALL

SELECT 
	LCODE, 
	'MONTH'=MONTH(CONVERT(SMALLDATETIME,CONVERT(VARCHAR,DATE))),
	'YEAR'=YEAR(CONVERT(SMALLDATETIME,CONVERT(VARCHAR,DATE))),
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '01' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D1', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '02' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D2', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '03' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D3', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '04' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D4', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '05' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D5', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '06' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D6', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '07' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D7', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '08' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D8', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '09' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D9', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '10' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D10', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '11' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D11', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '12' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D12', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '13' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D13', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '14' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D14', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '15' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D15', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '16' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D16', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '17' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D17', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '18' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D18', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '19' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D19', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '20' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D20', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '21' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D21', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '22' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D22', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '23' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D23', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '24' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D24', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '25' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D25', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '26' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D26', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '27' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D27', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '28' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D28', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '29' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D29', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '30' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D30', 
	(CASE WHEN SUBSTRING(CONVERT(VARCHAR(8),DATE),7,2) = '31' THEN  SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS) ELSE 0 END) AS 'D31',
	NETBOOKINGS=SUM(CAR_BOOKINGS) + SUM(HOTEL_BOOKINGS)
FROM T_C_1A_DAILY_BOOKINGS3 WITH(NOLOCK)
GROUP BY
	LCODE,DATE) AS B
GROUP BY LCODE,[MONTH],[YEAR]





GO

/****** Object:  View [dbo].[VW_AIRLINEWISE_MARKETSHARE]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_AIRLINEWISE_MARKETSHARE] AS 
SELECT CT.CITY_NAME,A.AIRLINE_CODE,ONLINE_CARRIER,M.DATE,'AIRLINENAME'=RTRIM(LTRIM(A.NAME)),'CRS'=CRSCODETEXT,'BOOKINGACTIVE'=SUM(BA),'CANCELACTIVE'=SUM(XA),'BOOKINGPASSIVE'=SUM(BP),'CANCELPASSIVE'=SUM(XP),'LATE'=SUM(LATE),'NULLACTIVE'=SUM(NA),'NULLPASSIVE'=SUM(NP),'NETBOOKINGS'=SUM(NETBOOKINGS) 
FROM 
	T_MIDTPRODUCTIVITY_AIR2  M WITH(NOLOCK) 
	INNER JOIN T_CRS C WITH(NOLOCK) ON  M.CRSCODE=C.CRSCODE
	INNER JOIN T_AIRLINE  A WITH(NOLOCK) ON M.AIRLINE_CODE=A.AIRLINE_CODE
	INNER JOIN T_G_CITY CT  WITH(NOLOCK) ON M.CITYID=CT.CITYID
--WHERE M.DATE BETWEEN '01/01/2009' AND '12/31/2009'  
GROUP BY CT.CITY_NAME,A.AIRLINE_CODE,A.NAME,ONLINE_CARRIER,M.DATE,CRSCODETEXT 

GO

/****** Object:  View [dbo].[VW_AIRNET]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_AIRNET] AS
	SELECT DATE=((YEAR*100)+MONTH)*100+1,'NETBOOKINGS' = SUM(NETBOOKINGS),LCODE,OFFICEID,MONTH,YEAR FROM  
	(			
	SELECT LCODE,OFFICEID,MONTH,YEAR,NETBOOKINGS=SUM(T_C_AIR_BOOKINGS.NETBOOKINGS) FROM T_C_AIR_BOOKINGS WITH (NOLOCK)
	INNER JOIN LOCATION_MASTER WITH (NOLOCK) ON T_C_AIR_BOOKINGS.LCODE = LOCATION_MASTER.LOCATION_CODE   		
	--WHERE (CAST(T_C_AIR_BOOKINGS.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(T_C_AIR_BOOKINGS.MONTH AS VARCHAR(2)) ,2)) 	BETWEEN  @FROMDATE AND @TODATE 
	--AND LCODE =27845 
	GROUP BY T_C_AIR_BOOKINGS.LCODE,OFFICEID,MONTH,YEAR 

	UNION ALL  

	SELECT APROD.LCODE,APROD.OFFICEID,APROD.MONTH,APROD.YEAR,NETBOOKINGS=T_C_1A_BOOKINGS.NETBOOKINGS-APROD.NETBOOKINGS 
	FROM  APROD WITH (NOLOCK)
	INNER JOIN LOCATION_MASTER WITH (NOLOCK) ON APROD.LCODE = LOCATION_MASTER.LOCATION_CODE 
	INNER JOIN T_C_1A_BOOKINGS WITH (NOLOCK) ON APROD.LCODE=T_C_1A_BOOKINGS.LCODE AND APROD.OFFICEID=T_C_1A_BOOKINGS.OFFICEID 
	AND APROD.MONTH=T_C_1A_BOOKINGS.MONTH  AND APROD.YEAR=T_C_1A_BOOKINGS.YEAR 		
--	WHERE  (CAST(APROD.YEAR AS VARCHAR(4)) + RIGHT('0' + CAST(APROD.MONTH AS VARCHAR(2)) ,2)) BETWEEN  @FROMDATE AND @TODATE --and  APROD.LCODE =27845 
	) AS D1  GROUP BY D1.LCODE,D1.OFFICEID,D1.MONTH,D1.YEAR 




GO

/****** Object:  View [dbo].[VW_BR_AGROUP]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_BR_AGROUP] AS
SELECT 
	BR_AG.OFFICEID,BR_AG.NAME,'ADDRESS'= 
CASE WHEN LEN(LTRIM(RTRIM(ADDRESS1)))=0 THEN BR_AG.ADDRESS ELSE BR_AG.ADDRESS +', '+ ISNULL(BR_AG.ADDRESS1,'') END ,C.CITYID,BR_AG.AOFFICE,BR_AG.PANNO
 FROM
(
	SELECT OFFICEID,NAME,AOFFICE,ADDRESS,ADDRESS1,PANNO,CITY_NAME,COUNTRY_NAME FROM [192.168.2.28].BIRDRES.DBO.VW_BR_LOCATION_MASTER 
	WHERE MAIN_AGENT=OFFICEID
) AS BR_AG
INNER JOIN
	(SELECT 
		C.CITYID,C.CT_CODE,CITY=C.CT_NAME,C.CO_CODE,C.AOFFICE,COUNTRY=CO_NAME 
	FROM T_BR_MS_CITY C WITH(NOLOCK)
	INNER JOIN T_BR_MS_COUNTRY CN WITH(NOLOCK) ON C.CO_CODE=CN.CO_CODE) AS C ON BR_AG.CITY_NAME=C.CITY AND BR_AG.COUNTRY_NAME=C.COUNTRY

GO

/****** Object:  View [dbo].[VW_FEASIBLEDETAILS]    Script Date: 04/28/2011 15:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_FEASIBLEDETAILS] AS 
SELECT REQUESTID,ISPID,FEASIBLESTATUSID,FEASIBLEDATE,MAILSENDDATETIME FROM T_G_ISP_FEASIBLE_DETAILS
UNION ALL
SELECT 
REQUESTID,NULL AS ISPID,3 AS FEASIBLESTATUSID,NULL AS FEASIBLEDATE, NULL  AS MAILSENDDATETIME
FROM T_G_ISP_FEASIBLE_REQUEST F WHERE NOT EXISTS
(SELECT * FROM T_G_ISP_FEASIBLE_DETAILS D WHERE F.REQUESTID=D.REQUESTID)





GO

/****** Object:  View [dbo].[VW_GET_GP_HARDWARE]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--DROP VIEW VW_GET_GP_HARDWARE
--SELECT * FROM VW_GET_GP_HARDWARE

CREATE VIEW [dbo].[VW_GET_GP_HARDWARE] AS
SELECT A.CHAIN_CODE,A.CHAIN_NAME,'NO_OF_PC'=SUM(NO_OF_PC),'NO_OF_PRINTER'=SUM(NO_OF_PRINTER),NO_OF_TICKET=SUM(NO_OF_TICKET) FROM
(SELECT LOCATION_MASTER.CHAIN_CODE,CHAIN_NAME,
'NO_OF_PC'=COUNT(LOCATION_CODE),'NO_OF_PRINTER'=0,'NO_OF_TICKET'=0
FROM LOCATION_MASTER WITH(NOLOCK) , PCINSTALLATION WITH(NOLOCK), AGROUP WITH(NOLOCK) 
WHERE LOCATION_CODE = LCODE AND AGROUP.CHAIN_CODE=LOCATION_MASTER.CHAIN_CODE
GROUP BY LOCATION_MASTER.CHAIN_CODE,CHAIN_NAME

UNION ALL
SELECT LOCATION_MASTER.CHAIN_CODE, CHAIN_NAME,
'NO_OF_PC'=0,'NO_OF_PRINTER'=COUNT(LOCATION_CODE),'NO_OF_TICKET'=0 
FROM LOCATION_MASTER WITH(NOLOCK),
MISCINSTALLATION WITH(NOLOCK),
EQUIPMENT_MASTER WITH(NOLOCK), AGROUP WITH(NOLOCK)  
WHERE  LOCATION_CODE = LCODE AND 
LCODE =LOCATION_CODE 
AND EGROUP_CODE = 'DPR' 
AND EQUIPMENT_TYPE = EQUIPMENT_CODE 
AND AGROUP.CHAIN_CODE=LOCATION_MASTER.CHAIN_CODE
GROUP BY LOCATION_MASTER.CHAIN_CODE,CHAIN_NAME

UNION ALL
SELECT LOCATION_MASTER.CHAIN_CODE, CHAIN_NAME,
'NO_OF_PC'=0,'NO_OF_PRINTER'=COUNT(LOCATION_CODE),'NO_OF_TICKET'=COUNT(LOCATION_CODE)
FROM 
LOCATION_MASTER WITH(NOLOCK),
MISCINSTALLATION WITH(NOLOCK),
EQUIPMENT_MASTER WITH(NOLOCK) , AGROUP WITH(NOLOCK) 
WHERE  LOCATION_CODE = LCODE AND LCODE =LOCATION_CODE AND EGROUP_CODE = 'TPR' 
AND EQUIPMENT_TYPE = EQUIPMENT_CODE AND AGROUP.CHAIN_CODE=LOCATION_MASTER.CHAIN_CODE
GROUP BY LOCATION_MASTER.CHAIN_CODE,CHAIN_NAME) AS A
GROUP BY A.CHAIN_CODE,A.CHAIN_NAME



GO

/****** Object:  View [dbo].[VW_GROUP_INCENTIVE_DETAILS]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_GROUP_INCENTIVE_DETAILS] AS
SELECT A.CHAIN_CODE,Group_Classification_Name,'INCHARGE'=E.EMPLOYEE_NAME,TOTAL_LOCATIONS=T.TOTAL,ONLINE_LOCATION_1A,'ON_CONTRACT_WITH_1A'='','CONTRACT_EFFECTIVE_DATE'='','EXPIRY'='' FROM AGROUP A
LEFT OUTER JOIN
	(
	SELECT B.CHAIN_CODE,'TOTAL'=COUNT(*) FROM AGROUP B WITH(NOLOCK)
	INNER JOIN LOCATION_MASTER LM WITH(NOLOCK) ON LM.CHAIN_CODE=B.CHAIN_CODE
	GROUP BY B.CHAIN_CODE
	) AS T ON A.CHAIN_CODE=T.CHAIN_CODE
LEFT OUTER JOIN
	(
	SELECT B.CHAIN_CODE,'ONLINE_LOCATION_1A'=COUNT(*) FROM AGROUP B WITH(NOLOCK)
	INNER JOIN LOCATION_MASTER LM WITH(NOLOCK) ON LM.CHAIN_CODE=B.CHAIN_CODE
	WHERE LM.ONLINE_STATUS NOT IN('CXLD','DE') AND ONLINE_STATUS IS NOT NULL
	GROUP BY B.CHAIN_CODE
	) AS O ON A.CHAIN_CODE=O.CHAIN_CODE
LEFT OUTER JOIN T_G_EMPLOYEES E WITH(NOLOCK) ON A.ACCOUNTMANAGER=E.EMPLOYEEID
LEFT OUTER JOIN T_C_CLASSIFICATION C WITH(NOLOCK) ON A.GROUPCLASSIFICATIONID=C.GROUPCLASSIFICATIONID




GO

/****** Object:  View [dbo].[VW_GRPPRD_CHAINCODE]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_GRPPRD_CHAINCODE] AS
SELECT GRP_CHAINCODE,GRP_EEMPLOYEEID,GRP_LCODE,GRP_AGENCYNAME,EMP_GROUPTYPEID,GR_GROUPTYPEID FROM
 (
	SELECT 
	'GRP_CHAINCODE'=T_G_EMP_AGENCY_GROUP.CHAIN_CODE,
	'GRP_LCODE'=LOCATION_MASTER.LOCATION_CODE,
    'GRP_EEMPLOYEEID'=T_G_EMP_AGENCY_GROUP.EMPLOYEEID, 
	'GRP_AGENCYNAME'=LOCATION_MASTER.NAME, 
	'EMP_GROUPTYPEID'=T_G_EMPLOYEES.GROUPTYPEID,
	'GR_GROUPTYPEID'=AGROUP.GROUPTYPEID
	FROM T_G_EMP_AGENCY_GROUP WITH(NOLOCK)
	INNER JOIN LOCATION_MASTER  WITH(NOLOCK) ON  LOCATION_MASTER.CHAIN_CODE=T_G_EMP_AGENCY_GROUP.CHAIN_CODE
	INNER JOIN T_G_EMPLOYEES  WITH(NOLOCK) ON T_G_EMPLOYEES.EMPLOYEEID=T_G_EMP_AGENCY_GROUP.EMPLOYEEID
	INNER JOIN AGROUP  WITH(NOLOCK) ON AGROUP.CHAIN_CODE=T_G_EMP_AGENCY_GROUP.CHAIN_CODE
	--WHERE T_G_EMP_AGENCY_GROUP.EMPLOYEEID = 202526 	AND LOCATION_CODE=13634
) AS A
WHERE 
	EMP_GROUPTYPEID IS NULL OR	ISNULL(EMP_GROUPTYPEID,0)=ISNULL(GR_GROUPTYPEID,0)


GO

/****** Object:  View [dbo].[VW_HD_GET_FEEDBACK_DETAILS]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_HD_GET_FEEDBACK_DETAILS] AS
SELECT 
		FEEDBACK_ID,
		STATUS_HELPDESK=MAX(STATUS_HELPDESK),
		STATUS_TECHNICAL=MAX(STATUS_TECHNICAL),
		STATUS_SALES=MAX(STATUS_SALES),
		STATUS_TRAINING=MAX(STATUS_TRAINING),
		STATUS_PRODUCT=MAX(STATUS_PRODUCT),
		STATUS_CCOMMUNICATION=MAX(STATUS_COMMUNICATION),
		ASSIGNEDTO_HELPDESK=MAX(ASSIGNEDTO_HELPDESK),
		ASSIGNEDTO_TECHNICAL=MAX(ASSIGNEDTO_TECHNICAL),
		ASSIGNEDTO_SALES=MAX(ASSIGNEDTO_SALES),
		ASSIGNEDTO_TRAINING=MAX(ASSIGNEDTO_TRAINING),
		ASSIGNEDTO_PRODUCT=MAX(ASSIGNEDTO_PRODUCT),
		ASSIGNEDTO_CCOMMUNICATION=MAX(ASSIGNEDTO_CCOMMUNICATION),
		HELPDESK_CRITICAL=MAX(HELPDESK_CRITICAL),
		TECHNICAL_CRITICAL=MAX(TECHNICAL_CRITICAL),
		SALES_CRITICAL=MAX(SALES_CRITICAL),
		TRAINING_CRITICAL=MAX(TRAINING_CRITICAL),
		PRODUCTS_CRITICAL=MAX(PRODUCTS_CRITICAL),
		CC_CRITICAL=MAX(CC_CRITICAL)
	FROM(
		SELECT FEEDBACK_ID
			,STATUS_HELPDESK=CASE WHEN FBD.SUG_DEPT_ID=1 THEN FEEDBACK_STATUS_NAME ELSE '' END
			,STATUS_TECHNICAL=CASE WHEN FBD.SUG_DEPT_ID=2 THEN FEEDBACK_STATUS_NAME ELSE '' END
			,STATUS_SALES=CASE WHEN FBD.SUG_DEPT_ID=3 THEN FEEDBACK_STATUS_NAME ELSE '' END
			,STATUS_TRAINING=CASE WHEN FBD.SUG_DEPT_ID=4 THEN FEEDBACK_STATUS_NAME ELSE '' END
			,STATUS_PRODUCT=CASE WHEN FBD.SUG_DEPT_ID=5 THEN FEEDBACK_STATUS_NAME ELSE '' END
			,STATUS_COMMUNICATION=CASE WHEN FBD.SUG_DEPT_ID=6 THEN FEEDBACK_STATUS_NAME ELSE '' END

			,ASSIGNEDTO_HELPDESK=CASE WHEN FBD.SUG_DEPT_ID=1 THEN EMP1.EMPLOYEE_NAME ELSE '' END
			,ASSIGNEDTO_TECHNICAL=CASE WHEN FBD.SUG_DEPT_ID=2 THEN EMP1.EMPLOYEE_NAME ELSE '' END
			,ASSIGNEDTO_SALES=CASE WHEN FBD.SUG_DEPT_ID=3 THEN EMP1.EMPLOYEE_NAME  ELSE '' END
			,ASSIGNEDTO_TRAINING=CASE WHEN FBD.SUG_DEPT_ID=4 THEN EMP1.EMPLOYEE_NAME  ELSE '' END
			,ASSIGNEDTO_PRODUCT=CASE WHEN FBD.SUG_DEPT_ID=5 THEN EMP1.EMPLOYEE_NAME  ELSE '' END
			,ASSIGNEDTO_CCOMMUNICATION=CASE WHEN FBD.SUG_DEPT_ID=6 THEN EMP1.EMPLOYEE_NAME  ELSE '' END


			,HELPDESK_CRITICAL=CASE WHEN FBD.SUG_DEPT_ID=1 THEN CRITICAL ELSE 0 END
			,TECHNICAL_CRITICAL=CASE WHEN FBD.SUG_DEPT_ID=2 THEN CRITICAL ELSE 0 END
			,SALES_CRITICAL=CASE WHEN FBD.SUG_DEPT_ID=3 THEN CRITICAL ELSE 0 END
			,TRAINING_CRITICAL=CASE WHEN FBD.SUG_DEPT_ID=4 THEN CRITICAL ELSE 0 END
			,PRODUCTS_CRITICAL=CASE WHEN FBD.SUG_DEPT_ID=5 THEN CRITICAL ELSE 0 END
			,CC_CRITICAL=CASE WHEN FBD.SUG_DEPT_ID=6 THEN CRITICAL ELSE 0 END
		FROM T_HD_FEEDBACKSUGGESTION_DETAILS FBD WITH(NOLOCK) 
		LEFT OUTER JOIN T_G_EMPLOYEES EMP1 WITH(NOLOCK) ON EMP1.EMPLOYEEID=FBD.ASSIGNEDTO
		LEFT OUTER JOIN T_HD_FEEDBACKSUGGESTION_STATUS FS WITH(NOLOCK) ON FBD.FEEDBACK_STATUS_ID=FS.FEEDBACK_STATUS_ID		
	) AS A
GROUP BY FEEDBACK_ID
GO

/****** Object:  View [dbo].[VW_INC_BC_PLAN_SLAB]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_INC_BC_PLAN_SLAB] AS
SELECT 
	P.BC_ID,
	BM.INC_TYPE_ID,
	IT.INC_TYPE_NAME,
	INC_SLAB_REQUIRED=CASE WHEN ISNULL(INC_SLAB_REQUIRED,'')='1' THEN 'TRUE' ELSE 'FALSE' END,
	P.INC_PLAN_ID,P.INC_PLAN_NAME	
	,[DBO].FN_GET_AIRLINEDATA_ID(P.BC_ID,P.INC_PLAN_ID) AS AIRLINEDATA_ID
	,[DBO].FN_GET_AIRLINEDATA(P.BC_ID,P.INC_PLAN_ID) AS AIRLINEDATA
	,PS.SLABS_START,PS.SLABS_END,PS.SLABS_RATE
FROM T_INC_BC_MASTER BM WITH(NOLOCK)
INNER JOIN T_INC_BC_INCENTIVE_PLAN P WITH(NOLOCK) ON  BM.BC_ID=P.BC_ID
INNER JOIN T_INC_INCENTIVE_TYPE IT WITH(NOLOCK) ON BM.INC_TYPE_ID=IT.INC_TYPE_ID
LEFT OUTER JOIN T_INC_BC_INCENTIVE_PLAN_SLABS PS WITH(NOLOCK) ON P.INC_PLAN_ID=PS.INC_PLAN_ID
GO

/****** Object:  View [dbo].[VW_MIDT]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_MIDT] AS  
SELECT   
 LM.CITY,  
 LM.AOFFICE,  
 LM.COUNTRY,  
 B.REGION,  
 CRS=CRSCODETEXT,   
 AIRLINE_CODE,  
 A.[DATE],  
 GT.GroupTypeID,  
 'PASSIVESEGMENTS'=SUM(BP)-SUM(XP),  
 'ACTIVESEGMENTS'=SUM(BA)-SUM(XA),   
 'TOTALSEGMENTS'= (SUM(BP)-SUM(XP))  + (SUM(BA)-SUM(XA))  
FROM T_MIDTPRODUCTIVITY_AIR A WITH (NOLOCK)  
INNER JOIN LOCATION_MASTER LM WITH(NOLOCK) ON LM.LOCATION_CODE=A.LCODE  
INNER JOIN AGROUP G WITH(NOLOCK) ON LM.CHAIN_CODE=G.CHAIN_CODE  
INNER JOIN T_CRS C WITH (NOLOCK) ON C.CRSCODE=A.CRSCODE   
INNER JOIN BRANCH B WITH(NOLOCK) ON B.AOFFICE=LM.AOFFICE  
LEFT OUTER JOIN T_G_GROUP_TYPE GT WITH(NOLOCK) ON G.GroupTypeID=GT.GroupTypeID  
GROUP BY  
  LM.CITY,LM.AOFFICE,LM.COUNTRY,B.REGION,CRSCODETEXT,AIRLINE_CODE,A.[DATE],GT.GroupTypeID   
    
GO

/****** Object:  View [dbo].[VW_MIDT_AIR]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_MIDT_AIR] AS 
SELECT LM.CHAIN_CODE,LCODE,LM.CITY,LM.AOFFICE,LM.COUNTRY,B.REGION,
A.AIRLINE_CODE,
'AIRLINENAME'=AL.NAME,
CRSCODETEXT,G.GROUPTYPEID,ONLINE_CARRIER,RESP_1A,
(((YEAR*100)+MONTH)*100)+1 AS DATE,XA,XP,BP,BA,NA,NP,LATE,NETBOOKINGS 
FROM T_MIDTPRODUCTIVITY_AIR A WITH(NOLOCK)
INNER JOIN LOCATION_MASTER LM WITH(NOLOCK) ON LM.LOCATION_CODE=A.LCODE
INNER JOIN AGROUP G WITH(NOLOCK) ON LM.CHAIN_CODE=G.CHAIN_CODE
INNER JOIN T_CRS CRS  WITH(NOLOCK) ON CRS.CRSCODE=A.CRSCODE
INNER JOIN T_AIRLINE AL  WITH(NOLOCK) ON AL.AIRLINE_CODE =A.AIRLINE_CODE
INNER JOIN BRANCH B WITH(NOLOCK) ON B.AOFFICE=LM.AOFFICE




GO

/****** Object:  View [dbo].[VW_MIDT_AIRLINE_BREAKUP]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_MIDT_AIRLINE_BREAKUP] AS 
SELECT DATE=(((YEAR*100)+MONTH)*100)+1,G.CHAIN_CODE,LCODE,AIRLINE_CODE,CRSCODE,NETBOOKINGS=SUM(NETBOOKINGS) FROM 
T_MIDTPRODUCTIVITY_AIR A WITH(NOLOCK)  
INNER JOIN LOCATION_MASTER LM WITH(NOLOCK)  ON LM.LOCATION_CODE=A.LCODE
INNER JOIN AGROUP G WITH(NOLOCK)  ON G.CHAIN_CODE=LM.CHAIN_CODE
GROUP BY (((YEAR*100)+MONTH)*100)+1,G.CHAIN_CODE,LCODE,AIRLINE_CODE,CRSCODE

GO

/****** Object:  View [dbo].[VW_NIDT_AGENCY_DETAILS]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_NIDT_AGENCY_DETAILS] AS  
SELECT   
G.CHAIN_CODE,G.CHAIN_NAME,C.LCODE, 'AGENCY_NAME'=LM.NAME,C.OFFICEID,LM.CITY,LM.AOFFICE,LM.COUNTRY  
FROM CRSUSE C WITH (NOLOCK)    
INNER JOIN LOCATION_MASTER LM WITH(NOLOCK) ON LM.LOCATION_CODE=C.LCODE  
INNER JOIN AGROUP G WITH(NOLOCK) ON LM.CHAIN_CODE=G.CHAIN_CODE  
WHERE   
--C.CURRENTID = 'Y' AND   
C.CRS = '1A'
GO

/****** Object:  View [dbo].[VW_NIDT_FIELDS_MINIMUM_SEGMENT]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_NIDT_FIELDS_MINIMUM_SEGMENT] AS 
SELECT NIDT_FIELDS_ID,NIDT_FIELDS_NAME=NIDT_FIELDS_ALIAS 
,'NIDT_FIELDS_CATEGORY_ID'=ROUND(ISNULL(NIDT_FIELDS_CATEGORY_ID,0)+ISNULL(NIDT_FIELDS_CATEGORYSUB_ID,0),0)
FROM T_INC_NIDT_FIELDS WITH(NOLOCK)
WHERE ISNULL(NIDT_FIELDS_CATEGORY_ID,0)+ISNULL(NIDT_FIELDS_CATEGORYSUB_ID,0) > 0
AND  ISNULL(NIDT_FIELDS_ALIAS,'CODD') NOT IN ('CODD')


GO

/****** Object:  View [dbo].[VW_OFF_MIDT]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_OFF_MIDT] AS
SELECT LCODE,OFFICEID,[MONTH],[YEAR],DATE=((([YEAR]*100)+[MONTH])*100)+1,NETBOOKINGS=SUM(NETBOOKINGS) 
FROM T_MIDTPRODUCTIVITY_AIR3 WITH(NOLOCK)
GROUP BY LCODE,OFFICEID,[MONTH],[YEAR]




GO

/****** Object:  View [dbo].[VW_T_MIDTPRODUCTIVITY_AIR]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_T_MIDTPRODUCTIVITY_AIR]
AS  
  
SELECT G.GROUPTYPEID,A.LCODE,A.MONTH,A.YEAR,A.AIRLINE_CODE,A.CRSCODE,A.DATE,A.NETBOOKINGS, TM.CITYID 
FROM T_MIDTPRODUCTIVITY_AIR A WITH (NOLOCK)
LEFT OUTER JOIN LOCATION_MASTER LM WITH (NOLOCK) ON   LM.LOCATION_CODE = A.LCODE  
LEFT OUTER JOIN AGROUP G WITH (NOLOCK)  ON LM.CHAIN_CODE = G.CHAIN_CODE      
LEFT OUTER JOIN  T_G_CITY TC WITH (NOLOCK) ON TC.CITY_NAME = LM.CITY
LEFT OUTER JOIN  T_MIDTPRODUCTIVITY_AIR2 TM WITH (NOLOCK) ON TM.CITYID= TC.CITYID
AND MONTH(TM.DATE) = A.MONTH AND YEAR(TM.DATE) = A.YEAR
AND TM.AIRLINE_CODE = A.AIRLINE_CODE  AND TM.CRSCODE = A.CRSCODE 

GO

/****** Object:  View [dbo].[VW_T_TR_COURSE_SESSION]    Script Date: 04/28/2011 15:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_T_TR_COURSE_SESSION]
AS 
	SELECT T_TR_COURSE_SESSION.* ,TRAINER1=T_G_EMPLOYEES.EMPLOYEE_NAME  ,TRAINER2=A.EMPLOYEE_NAME  FROM T_TR_COURSE_SESSION
	LEFT OUTER JOIN T_G_EMPLOYEES  ON T_TR_COURSE_SESSION.EMPLOYEE_ID1 =T_G_EMPLOYEES.EmployeeID
	LEFT OUTER JOIN T_G_EMPLOYEES  A ON T_TR_COURSE_SESSION.EMPLOYEE_ID2 =A.EmployeeID

GO


