USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_G_EmployeePasswordLog]    Script Date: 10/11/2011 15:16:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_G_EmployeePasswordLog](
	[EmployeeId] [int] NOT NULL,
	[OldPassword] [varchar](100) NULL,
	[NewPassword] [varchar](100) NULL,
	[ChangedDate] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_G_ACCESSLEVEL_Log]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_G_ACCESSLEVEL_Log](
	[EmployeeID] [int] NOT NULL,
	[ModifyBy] [int] NOT NULL,
	[SecurityOptionID] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[ChangedData] [varchar](1000) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_STYLE_ORDERS]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_STYLE_ORDERS](
	[W_StyleOrderID] [int] IDENTITY(1,1) NOT NULL,
	[W_StyleId] [int] NULL,
	[Qty] [int] NULL,
	[Remarks] [varchar](500) NULL,
	[LOGDATE] [datetime] NULL,
 CONSTRAINT [PK__W_STYLE_ORDERS__08EA5793] PRIMARY KEY NONCLUSTERED 
(
	[W_StyleOrderID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_G_SECURITY_OPTIONS]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_G_SECURITY_OPTIONS](
	[SecurityOptionID] [int] IDENTITY(1,1) NOT NULL,
	[SecurityOptionSubName] [varchar](100) NOT NULL,
	[Sec_Group_ID] [int] NOT NULL,
	[Image] [image] NULL,
 CONSTRAINT [PK__W_G_SECURITY_OPT__3D5E1FD2] PRIMARY KEY NONCLUSTERED 
(
	[SecurityOptionSubName] ASC,
	[Sec_Group_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_G_SECURITY_OPTION_GROUP]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_G_SECURITY_OPTION_GROUP](
	[Sec_Group_ID] [int] IDENTITY(1,1) NOT NULL,
	[Sec_Group] [varchar](100) NOT NULL,
 CONSTRAINT [PK_W_G_SECURITY_OPTION_GROUP] PRIMARY KEY CLUSTERED 
(
	[Sec_Group] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_G_ACCESSLEVEL]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[W_G_ACCESSLEVEL](
	[EmployeeID] [int] NOT NULL,
	[SecurityOptionID] [int] NOT NULL,
	[Value] [smallint] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[EmployeeID] ASC,
	[SecurityOptionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_G_EMPLOYEES]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_G_EMPLOYEES](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[FAX] [varchar](30) NULL,
	[Cell_Phone] [varchar](30) NULL,
	[Phone] [varchar](30) NULL,
	[Login] [char](20) NULL,
	[Email] [varchar](100) NULL,
	[Employee_Name] [char](40) NOT NULL,
	[IPRestriction] [bit] NULL,
	[Password] [varchar](300) NULL,
	[FirstForm] [varchar](100) NULL,
	[Deleted] [bit] NULL,
	[ChangePassword] [bit] NULL,
	[PwdLastChanged] [datetime] NULL,
	[PwdExpire] [bit] NULL,
	[FirstLoginDone] [bit] NULL,
 CONSTRAINT [PK__W_G_EMPLOYEES__145C0A3F] PRIMARY KEY NONCLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [AAMS_TEST]
GO

/****** Object:  Table [dbo].[W_STYLE]    Script Date: 10/11/2011 15:16:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[W_STYLE](
	[W_StyleId] [int] IDENTITY(1,1) NOT NULL,
	[BarcodeNo] [varchar](150) NULL,
	[StyleName] [varchar](50) NULL,
	[DesignNo] [varchar](50) NULL,
	[ShadeNo] [varchar](25) NULL,
	[MRP] [int] NULL,
 CONSTRAINT [PK_W_STYLE] PRIMARY KEY CLUSTERED 
(
	[W_StyleId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[W_G_EmployeePasswordLog] ADD  DEFAULT (getdate()) FOR [ChangedDate]
GO

ALTER TABLE [dbo].[W_G_ACCESSLEVEL_Log]  WITH CHECK ADD  CONSTRAINT [FK_W_G_ACCESSLEVEL_Log_W_G_EMPLOYEES] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[W_G_EMPLOYEES] ([EmployeeID])
GO

ALTER TABLE [dbo].[W_G_ACCESSLEVEL_Log] CHECK CONSTRAINT [FK_W_G_ACCESSLEVEL_Log_W_G_EMPLOYEES]
GO

ALTER TABLE [dbo].[W_G_ACCESSLEVEL_Log]  WITH CHECK ADD  CONSTRAINT [FK_W_G_ACCESSLEVEL_Log_W_G_EMPLOYEES1] FOREIGN KEY([ModifyBy])
REFERENCES [dbo].[W_G_EMPLOYEES] ([EmployeeID])
GO

ALTER TABLE [dbo].[W_G_ACCESSLEVEL_Log] CHECK CONSTRAINT [FK_W_G_ACCESSLEVEL_Log_W_G_EMPLOYEES1]
GO

ALTER TABLE [dbo].[W_STYLE_ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_W_STYLE_ORDERS_W_STYLE] FOREIGN KEY([W_StyleId])
REFERENCES [dbo].[W_STYLE] ([W_StyleId])
GO

ALTER TABLE [dbo].[W_STYLE_ORDERS] CHECK CONSTRAINT [FK_W_STYLE_ORDERS_W_STYLE]
GO

ALTER TABLE [dbo].[W_G_ACCESSLEVEL]  WITH NOCHECK ADD  CONSTRAINT [FK__W_G_ACCES__Emplo__44FF419A] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[W_G_EMPLOYEES] ([EmployeeID])
GO

ALTER TABLE [dbo].[W_G_ACCESSLEVEL] CHECK CONSTRAINT [FK__W_G_ACCES__Emplo__44FF419A]
GO


